events { worker_connections 1024; }

http {
    upstream api_cat {
        server cat:3000;
    }
    upstream api_dog {
        server dog:3000;
    }
    upstream api_all {
        server cat:3000;
        server dog:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_all;
        }

        location /cat {
            proxy_pass http://api_cat/;
        }

        location /dog {
            proxy_pass http://api_dog/;
        }
    }
}